FROM --platform=linux/amd64 golang:1.24-bookworm

# 安装编译依赖
RUN apt-get update && apt-get install -y libsoxr-dev pkg-config && rm -rf /var/lib/apt/lists/*

WORKDIR /build

COPY . .

# 编译 Linux amd64 版本
RUN GOOS=linux GOARCH=amd64 go build -o sip-proxy-linux-amd64

CMD ["ls", "-lh", "sip-proxy-linux-amd64"]
